version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /myApp/node_modules
      - .:/myApp
    env_file:
      - .env
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /myApp/node_modules
      - .:/myApp
    env_file:
      - .env